import type { LucideIcon } from "lucide-react";
import {
  BookOpen,
  Box,
  Briefcase,
  Calculator,
  CalendarCheck2,
  Code2,
  DollarSign,
  Dumbbell,
  Folder,
  Globe,
  GraduationCap,
  Heart,
  LayoutDashboard,
  PenLine,
  PiggyBank,
  Receipt,
  ShieldAlert,
  Sparkles,
  Target,
  TrendingDown,
  TrendingUp,
  Users,
  Wallet,
} from "lucide-react";

export const SPACE_ICON_MAP: Record<string, LucideIcon> = {
  BookOpen,
  Box,
  Briefcase,
  Calculator,
  CalendarCheck2,
  Code2,
  DollarSign,
  Dumbbell,
  Folder,
  Globe,
  GraduationCap,
  Heart,
  LayoutDashboard,
  PenLine,
  PiggyBank,
  Receipt,
  ShieldAlert,
  Sparkles,
  Target,
  TrendingDown,
  TrendingUp,
  Users,
  Wallet,
};

export function spaceIcon(name?: string): LucideIcon {
  return SPACE_ICON_MAP[name || ""] || Folder;
}